### ISSUE TITLE
appropriate-casey corrupts text

### ISSUE THREAD

**Issue by bil-bas** [diminish7/rave#1]
Although casey seems to attempt only to change text that it should, it often corrupts that text in doing so. I think this is largely because it breaks the cardinal rule of altering a string (specifically deleting characters) at the same time as iterating through its characters.

**Comment by bil-bas** [comment]
I was looking at the text operations yesterday and it struck me that they could be pretty buggy in certain circumstances. I'll throw some more tests at them when I get around to it.

**Comment by diminish7** [comment]
Changed to a) use BLIP_SUBMITTED instead of DOCUMENT_CHANGED and b) use event.blip instead of context.blips. Updated the README to match
