### ISSUE TITLE
Look into making use of appengine-jruby gem

### ISSUE THREAD

**Issue by diminish7** [diminish7/rave#10]

**Comment by bil-bas** [comment]
Although not directly involved in this issue, it would be nice if we could incorporate appcfg so we could upload files without requiring the user to install the whole appstore SDK. Hopefully this is included in the appengine gem, but if not, I think it would be nice to pull it in ourselves.

**Comment by diminish7** [comment]
Yeah, it's included in the appengine-jruby gem

**Comment by diminish7** [comment]
Decided against using the appengine jruby gem, it was overkill for what little we needed to use it for. You can still include that gem in your robot if you want to make use of the appengine api.
