### ISSUE TITLE
rename spooner-test

### ISSUE THREAD

**Issue by bil-bas** [diminish7/rave#13]
Well, I think this is a good test of Rave, since it exercises quite a lot of the API. Still, it needs a proper name, but I really can't think of one. After it has a name, we need to decide who hosts it at appspot. It would make sense for you to do so, to keep control over it, but since you are limited to 10 apps I'm not sure you want to commit yourself (and it does say you can't delete them, but it also says you can).

Also, I need to add some spec tests to it. Had quite a few times when I've uploaded it just to find there is a silly error.

**Comment by diminish7** [comment]
Let's just call it something like general_test_bot or api_exercise, or something. I mean, that's basically all it is, is an exercise of the API, right? And I'd be happy to host it on my appspot account if you want.

**Comment by bil-bas** [comment]
I'd suggest something prefixed with "rave" if they are entirely un-practical. That way, we can have rave-crony and rave-testy (for your cron example and my spooner-test, perhaps?). Appropriate-casey is a fine as it is, since although it isn't something anyone would really want, it does do one thing well (and I do think it will work better when we get ops working properly, such as implementing gsub! method on the blip itself to generate the correct operations. Well, whatever you think is good is fine for me; feel free to make the name-change whenever you want. I'll continue uploading each of the examples to spooner-test anyway.

Incidentally, a "practical" bot I was considering was textiley (textile markup). Depends whether I can find a textile-parser that can easily work as a back-end, but there are so many for Ruby, I'm sure one would be implemented correctly.

**Comment by diminish7** [comment]
Renamed spooner-test to rave-all-event-test-bot.  Maybe a bit verbose, but I think descriptive enough :)  It's deployed under that name as well now.
