### ISSUE TITLE
Get Rave working in MRI

### ISSUE THREAD

**Issue by diminish7** [diminish7/rave#17]
Currently only works in JRuby because all robots have to be deployed to appengine, but that won't always be the case, so we should make sure that it runs in MRI as a simple rack app.

**Comment by bil-bas** [comment]
I'm surprised this wasn't always the intention, since if we were going to always be limited to using the JRuby on appstore, we might as well have just made a Ruby wrapper around the Java wave robot API.

**Comment by diminish7** [comment]
This is working now - all tests pass in both jruby and mri, and a local server yields the correct results for mri. Can't test mri working with a real wave server for now, but it should all work.
