### ISSUE TITLE
Rename spec files to follow standards

### ISSUE THREAD

**Issue by bil-bas** [diminish7/rave#22]
RSpec files should be renamed:

  /spec/model/test__.rb => /spec/models/__spec.rb

However, whenever I tried this, even using 'git mv' or TortoiseGit 'rename', the history was lost.

I've rolled back and recommited everything without the filename changes, but I think this would be worth doing if we can do it safely.

**Comment by diminish7** [comment]
Looks like it is keeping the history, but the diff is showing everything different when you rename a file. Which sort of makes sense, I guess, if the diff is diff'ing files, not git history. Anyway, my main concern was keeping history, so I'm fine with the diff the way it is.
