### ISSUE TITLE
Reassess access to Context

### ISSUE THREAD

**Issue by bil-bas** [diminish7/rave#25]
I'm not sure that the context object should be passed to the robot handlers. Event should contain all the information you actually need in any use case I can think of (and that makes more sense to me anyway). You can always traverse the data to get to something you need (event.blip.wave.root_wavelet.root_blip.child_blips[2].child_blips.first, etc). The methods of use to the robot-creator are all about allowing you to dereference IDs anyway and they shouldn't be important anyway.

If you can think of any use-cases, other than in developing the API itself, where it might be useful, then I'm more than happy to keep it of course. Might have just overlooked something obvious, so I'm just really putting this up for discussion before I do anything drastic.

**Comment by diminish7** [comment]
Let's not make any changes to this until I've implemented the cron stuff.  I feel like the event info in the cron events will not be very useful, and the context will contain most of the information in that case. And I'd like to keep event handling similar for the two types of events.

**Comment by bil-bas** [comment]
Fair enough. Still no idea how the cron works. Waiting for you to do something with it so I can see how it works ;)

**Comment by diminish7** [comment]
Yeah me too :)

I've been working on it this morning. So far it's a been a pain in the ass. I'm reading stuff from a lot of people saying it's been hard to work with in both the Java and the Python API's. Hopefully I can make it easier in Rave....

**Comment by diminish7** [comment]
Leaving the context as is for now.
