### ISSUE TITLE
Users can prevent required gems from being used

### ISSUE THREAD

**Issue by bil-bas** [diminish7/rave#33]
http://github.com/diminish7/rave/commit/d03019b5ed47b0a31d8697d477cd3966cad9c4ba

Unfortunately, this method breaks things quite badly:
- Any existing projects will need to have this list manually added or have the project remade.
- If we want to add/remove gems to be used by rave itself, it is the _user's_ responsibility to update the list of gems.

The list of gems copied should be gems_required_by_rave (that is, what it was before) PLUS gems_required_by_user's_robot (how it is now), rather than have the whole list managed by the end-user. I think the config.yaml should have a section in it commented out, since it is hard to have an empty array already in the yaml (you can just have "gems: []", but that makes it harder to add more gems after it if the user isn't so comfortable with yaml syntax):

<pre><code class="yaml">
# Uncomment this section to add gems required by your robot to the data deployed.
# gems:
#   - required_gem_1 # Replace this name with the name of the gem you require.
#   - required_gem_2 # Replace this name with the name of the gem you require.
</code></pre>

**Comment by diminish7** [comment]
Done
