### ISSUE TITLE
jars should not be put in project

### ISSUE THREAD

**Issue by bil-bas** [diminish7/rave#34]
The jars should not be put into the project folder created for the user ("rave create"). They should only be copied into the tmp folder when performing "rave build". This would allow us to update the jar files as and when we want, without needing to rely on the user changing the files locally (they will be changed in the gem anyway).

For example, the Java API is now at 1.3.0 and we shouldn't have to make users perform this update if we can easily manage it entirely at our side of the system.

**Comment by diminish7** [comment]
Turns out that warbler takes care of breaking up jruby into smaller jars for us (we used to have to do that ourselves) so I was able to get the jruby jars out of this project altogether. And I got rid of the appengine jar from the robots and moved it over to the tmp/war folder at war time only.
