### ISSUE TITLE
Operations don't record current state when created

### ISSUE THREAD

**Issue by bil-bas** [diminish7/rave#36]
One issue with generating a number of operations over a number of events is that their state is only recorded when being sent. However, the data in the operation should definitely be recorded when created, not later, since the state may well have changed in the meantime. That is, a string should be written when the operation is created (in initialize), stored for when the operations are serialised (to_json), rather than being generated later in to_json itself.

**Comment by diminish7** [comment]
I'm not seeing any class where we aren't setting the data on initialize. Either you've already fixed this, or I'm not understanding the issue.  I'm closing this out, but let me know if this is still an issue (and if so, point me at a specific example of what you're talking about)  Thanks!
