### ISSUE TITLE
replacing to_json is problematic

### ISSUE THREAD

**Issue by bil-bas** [diminish7/rave#37]
Creating to_json on user-created classes is fine and dandy. The problem comes when standard classes are given overloaded to_json. Although this streamlines the code, it might cause problems when the user wants to communicate with external applications in json and suddenly standard classes like Range aren't being serialised in expected ways.

Either:
- Replace all to_json with to_rave_json (strictly, wave json is not serialised in the same way as ruby json operates, since it requires you to manage java-specific structures unnecessary in json itself).
- Manually convert standard classes when needed, rather than using to_json on them.

Currently only Range has to_json replaced (in blip text operations), but Array (in WAVELET_CREATE) is being manually converted to avoid this very issue. Hash could also benefit from being converted in certain circumstances, but it could not have its to_json replaced, since all the other classes uses its standard behaviour in their to_json routines.

**Comment by diminish7** [comment]
Stopped overriding to_json in range.  Added a to_rave_hash method. Before serialization in an operation, etc, to_rave_hash gets called if the item responds to that method.  This way we can still have the default to_json functionality in range without having to re-implement recursive to_json serialization with a to_rave_json strategy.
