### ISSUE TITLE
Problem deploying to appspot via rake/rave

### ISSUE THREAD

**Issue by bil-bas** [diminish7/rave#9]
Guess I'm doing something wrong, but calling the appstore uploader from within rake stops you entering your email/password. It is fine if you deploy by writing the command yourself the first time, since it remembers your details while you are logged in. Still, definitely makes it a bit pointless using rake for that. Surely there is a way to manage interactivity with Rake?

**Comment by diminish7** [comment]
I think this issue will become obsolete if we start making use of the appengine-jruby gem. I'll add an issue for that. I'm leaving this open because I'm not positive appengine-jruby will fix everything

**Comment by diminish7** [comment]
I'm closing this out in favor of the "rave appengine_deploy" command, which is working now

**Comment by bil-bas** [comment]
Sadly, although deploy works fine if you have put your email and password in, since this is using system command just like when it was running from regular rake. So not actually fixed in any way!

**Comment by diminish7** [comment]
I'm closing this out, but can you test again with what I just pushed? It's really weird, but the only thing I changed was expanding the path of the jar, and it works correctly for me now...  I have no explanation...  Can you test and see if it works on windows now too?  Thanks.
